Import('env', 'plugins')

plugins += env.SharedLibrary('homogeneous', ['homogeneous.cpp'])
plugins += env.SharedLibrary('heterogeneous', ['heterogeneous.cpp'])
plugins += env.SharedLibrary('nanovdbmedium', ['nanovdbmedium.cpp'])

Export('plugins')
